<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>test</groupId>
    <artifactId>five-vulns-maven</artifactId>
    <version>1.0.0</version>
    <packaging>pom</packaging>

    <!-- 5 Maven artifacts, each with exactly one CVE -->
    <dependencies>
        <dependency>
            <groupId>org.geysermc.geyser</groupId>
            <artifactId>core</artifactId>
            <version>2.9.2</version> <!-- CVE-2026-42188 -->
        </dependency>
        <dependency>
            <groupId>org.dromara.warm</groupId>
            <artifactId>warm-flow-plugin-modes-sb</artifactId>
            <version>1.8.4</version> <!-- CVE-2026-6125 -->
        </dependency>
        <dependency>
            <groupId>com.vaadin</groupId>
            <artifactId>flow-gradle-plugin</artifactId>
            <version>25.1.4</version> <!-- CVE-2026-7860 -->
        </dependency>
        <dependency>
            <groupId>org.mengyun</groupId>
            <artifactId>tcc-transaction</artifactId>
            <version>2.1.0</version> <!-- CVE-2026-9497 -->
        </dependency>
        <dependency>
            <groupId>com.github.ulisesbocchio</groupId>
            <artifactId>jasypt-spring-boot</artifactId>
            <version>4.0.4</version> <!-- CVE-2026-9370 -->
        </dependency>
    </dependencies>

</project>
